### PR TITLE
fix: serde wasm32 target

### LINKED ISSUE #277: Should not use cosmwasm_std::{to_vec, from_slice} other than WASM target
`cosmwasm_std::{to_vec, from_slice}` seems to use serde-json-wasm and it seems to have some bug.

```
error: entered unreachable code', /XXXXXXXX/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-json-wasm-0.4.1/src/de/mod.rs:586:9
```

(It is caused by deserializing a slice to `HashMap<String, CalleeProperty>`)

So we should not use `cosmwasm_std::{to_vec, from_slice}` other than WASM target, for example, cosmwasm_vm. We need to check and fix it is not used other than WASM target. For other than WASM target, use `serde_json::{to_vec, from_slice}` instead.

### PR DESCRIPTION
**Pull request by dudong2**
# Description

The `cosmwasm_std::{to_vec, from_slice}` were implemented using to `serde_json_wasm::{to_vec, from_slice}`. If it isn't a `WASM target`, using those functions may cause problems.

`contracts`, `packages/std` are wasm targets and `packages/derive`, `packages/storage` have a dependency on contracts.
`packages/vm` is not a wasm target.

So the change in this PR is to change the part of packages/vm that uses `cosmwasm_std::{to_vec, from_slice}` to `serde_json` based.

Closes #277 

## Types of changes

- [x] Bug fix (changes which fixes an issue)
- [ ] New feature (changes which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] ETC (build, ci, docs, perf, refactor, style, test)

## Checklist

- [x] I followed the [contributing guidelines](https://github.com/line/cosmwasm/blob/main/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] The PR title and commits are followed [conventional commit form](https://www.conventionalcommits.org/en/v1.0.0).

### CODE REVIEW

File: packages/vm/src/testing/querier.rs [hunk 1]
```diff
@@ -2,10 +2,11 @@ use serde::de::DeserializeOwned;
 
 use cosmwasm_std::testing::{MockQuerier as StdMockQuerier, MockQuerierCustomHandlerResult};
 use cosmwasm_std::{
-    to_binary, to_vec, Binary, Coin, ContractResult, CustomQuery, Empty, Querier as _,
```
Comment (loloicci) [inline packages/vm/src/testing/querier.rs:5]: `to_binary` is also serde serializing function. How about replacing it, too?

**Review by loloicci — APPROVED** [review]
LGTM!

**Review by loloicci — APPROVED** [review]

**Review by da1suk8 — APPROVED** [review]
